- name: Development Machine
  hosts: localhost
  vars_files:
    - vars/common.yaml
    # Must be created before executing.
    - vars/user.yaml
  roles:
    # Must happen first to pull private repositories later.
    - ssh
    - common
    - role: homebrew
      when: ansible_facts['os_family'] == "Darwin"
    - rust
    - gnupg
    - dotfiles
    - role: darwin
      when: ansible_facts['os_family'] == "Darwin"
    - vscode
