- name: Create temporary artifact directory
  tempfile:
    state: directory
    suffix: artifacts
  register: temp
  tags:
    - dotfiles-only

- name: Downloads rescript lsp bundle
  get_url:
    url: "{{ rescript_pkg_location }}"
    dest: "{{ temp.path }}/rescript-vscode.vsix"
    checksum: md5:a703213c829d2ed7d5e3ab0e760e8cd4

- name: Extracts extension bundle to artifact directory
  unarchive:
    src: "{{ temp.path }}/rescript-vscode.vsix"
    dest: "{{ third_party_pkg }}/rescript-vscode"

- name: Check if an exclusion list is provided by dotfiles
  stat:
    path: "{{ dotfiles_path }}exclude.txt"
  register: dotfiles_exclusion_list
  tags:
    - dotfiles-only

- name: Creating a file with content
  copy:
    dest: "{{ temp.path }}/exclude.txt"
    content: "{{ exclude | join('\n') }}"
  register: exclusion_list
  when: not dotfiles_exclusion_list.stat.exists
  tags:
    - dotfiles-only

- name: Sync dotfiles
  synchronize:
    delete: false
    src: "{{ dotfiles_path }}"
    dest: "{{ ansible_env.HOME }}"
    perms: false
    recursive: true
    rsync_opts:
      - "-v"
      - "--exclude-from={{ dotfiles_exclusion_list.stat.exists | ternary(dotfiles_exclusion_list.stat.path, exclusion_list.dest) }}"
  tags:
    - dotfiles-only
  notify: Run post install script

- meta: flush_handlers

- name: Delete temp directory
  file:
    state: absent
    path: "{{ temp.path }}"

- name: Create neovim autoload directory
  file:
    path: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload"
    state: directory

- name: Install neovim package manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"
    mode: "u=rw-,g=rw-,o=r--"
