- name: Copy default VS Code settings
  synchronize:
    delete: false
    src: "."
    # Jumping through some hoops here to make the space in the path behave on OSX.
    dest: '{{ ansible_env.HOME + "/Library/Application" + "\ " + "Support/Code/User/" }}'

- name: Installs VS Code extensions
  command: code --install-extension {{ item }}
  with_items: '{{ extensions }}'
  ignore_errors: yes
