- name: Copies platform specific GPG configs
  template: src="{{ ansible_os_family }}_{{ item }}" dest="{{ ansible_env.HOME }}/.gnupg/{{ item }}"
  loop:
    - gpg.conf
    - scdaemon.conf
    - gpg-agent.conf
