- name: Update coreutils
  homebrew:
    name: "{{ item }}"
    state: latest
  loop:
    - coreutils
    - ssh-copy-id
- name: Install Git
  homebrew:
    name: "{{ item }}"
    state: latest
  loop:
    - git-delta
    - git-absorb
- name: Install linters
  homebrew:
    name: "{{ item }}"
    state: latest
  loop:
    - pgformatter
    - tflint
    - gcc
    - ansible-lint
    - shellcheck
- name: Install MacOS binaries
  homebrew:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop:
    # Required to use keychain to store GPG key credentials.
    - name: pinentry-mac
      state: latest
