- name: Create temporary artifact directory
  tempfile:
    state: directory
    suffix: install
  register: temp
  tags:
    - init
    - never

- name: Download Homebrew installation script
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/master/install
    dest: "{{ temp.path }}/install"
  tags:
    - init
    - never

- name: Install Homebrew
  shell: /usr/bin/ruby "{{ temp.path }}/install" < /dev/null
  tags:
    - init
    - never

- name: Update Homebrew
  homebrew: update_homebrew=yes
  become: false
