# Layout common directories.
- name: Create static directory for readonly source code
  file:
    path: "{{ readonly_src }}"
    state: directory
    mode: "0777"
- name: Create static directory for readonly code artifacts
  file:
    path: "{{ third_party_pkg }}"
    mode: "0777"
    state: directory
- name: Create directory for rescript lsp
  file:
    path: "{{ third_party_pkg }}/rescript-vscode"
    mode: "0777"
    state: directory
- name: Create directory for user binaries
  file:
    path: "{{ ansible_env.HOME }}/bin"
    mode: "u=rwx,g=---,o=---"
    state: directory
- name: Create directory for user source code
  file:
    path: "{{ ansible_env.HOME }}/acx/sources"
    mode: "u=rwx,g=---,o=---"
    state: directory
- name: Clones active working directories
  git:
    repo: "git@github.com:{{ item }}.git"
    dest: "{{ third_party_src }}/github.com/{{ item }}"
    single_branch: yes
    # TODO(allancalix): Standardize upstream branch path to "main."
    version: master
  loop:
     - acx-dev/acx
     - acx-dev/kratos-ui
     - allancalix/dotfiles
