- name: Install system packages
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  shell: |
    set -euxo pipefail
    source ~/.nix-profile/etc/profile.d/nix.sh
    nix-env -i {{  item }}
  loop:
    - neovim
    - ripgrep
    - fd
    - exa
    - zoxide
    - fzf
    - bazelisk
    - tmux
    - bash
    - openssh

    - git
    - git-absorb
    - delta
    - gh

    - opam
    - go
    - fnm

    - vault
    - nomad
    - consul
    - terraform

    - postgresql
