- name: Installl prebuilt binaries from Neovim nightly
  get_url:
    url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
    dest: "{{ user_bin }}/nvim"
    mode: 0777
    force: "{{ neovim_update }}"
