name: Test
on:
  push: {}
jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Check full install playbook completes successfully
        env:
          XDG_CONFIG_HOME: $HOME/.config
        run: |
          cat <<EOF >>vars/user.yaml
          user_email: "test@example.com"
          dotfiles_path: "{{ third_party_src }}/github.com/allancalix/dotfiles/"
          EOF
          # cp tests/users.yaml vars/users.yaml
          sudo apt-get install unzip ansible # Installs requirements
          ansible-galaxy collection install -r requirements.yaml
          ansible-playbook --tags=all,init devmachine.yaml
