name: Test
on:
  push: {}
jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Check full install playbook completes successfully
        env:
          XDG_CONFIG_HOME: $HOME/.config
        run: |
          cp tests/user.yaml vars/user.yaml
          sudo apt-get install unzip ansible # Installs requirements
          ansible-galaxy collection install -r requirements.yaml
          # Do dotfiles sync only for now.
          ansible-playbook --tags=dotfiles-only devmachine.yaml
